### PR TITLE
Add XAML Island sample

### PR DESCRIPTION
**Pull request by fghzxm**
OK, so I half-copied and half-mimicked some windowing code from the D2D sample and it became kind of messy, but see if you have any more suggestions.

### CODE REVIEW

**Comment by kennykerr** [comment]
Agreed, its a little confusing given how much boilerplate is required and I'm not sure how much value this adds as an example. We're also moving toward the Windows App SDK as the preferred way to build desktop Xaml apps so perhaps we should just focus on those examples (#4).

**Comment by fghzxm** [comment]
If you don't see enough value in this example, maybe you could have told me that in microsoft/windows-rs#908.

**Comment by kennykerr** [comment]
Sorry hadn't actually looked past the PR title and toml dependencies and considering how much unrelated user32 scaffolding is required it just doesn't seem worthwhile. That's not a reflection on your code but more on the complexity of getting Xaml islands up and running, hence the suggestion to consider WinUI which seems a lot simpler.

**Comment by fghzxm** [comment]
It's still not clear to me, though do you mean by the time windows-rs and pals get feature-complete WinUI on Win32 will be ready and XAML Island will be deprecated?

If that's the case, I'll close the PR.

**Comment by kennykerr** [comment]
That certainly seems to be the direction Xaml is going.

**Pull request closed without merging**
