### PR TITLE
Test build warnings

### PR DESCRIPTION
**Pull request by kennykerr**
Test fix for #13

### CODE REVIEW

**Comment by wravery** [comment]
@kennykerr I think it might have passed the checks because the `run` step is a separate invocation. If you put that together with the `cargo test` command in a multi-line `script` step it'll emit a batch script where the environment variable is set for that process.

**Comment by wravery** [comment]
...although I'm not sure how portable that is, `pwsh` or `bash` might be better. Another way is apparently to add it to `.cargo/config`: https://stackoverflow.com/questions/56870422/how-can-i-cause-compilation-to-fail-on-warnings-on-ci-and-have-extra-rustflags-s.

**Comment by riverar** [comment]
@wravery Yup, working on it! We just discovered RUSTFLAGS are completely ignored when cross compiling which adds another dimension to the problem. 😂

**Comment by wravery** [comment]
Looks like a pretty old issue: https://github.com/rust-lang/cargo/issues/4423, most of the movement on that seems to be around making sure that compiling with `--target $host` works the same as the default by special casing that triplet.

Would it be sufficient to ignore that difference and only break the build for the host triplet? It looks like the https://github.com/rust-lang/cargo/pull/9322 PR was merged June 1st, so I would guess it's in the nightly branch at least. So if you set `RUSTFLAGS` consistently and it's ignored everywhere except when `--target` matches the host (and maybe only nightly for now), it should still fail at least one check.

**Comment by wravery** [comment]
> Would it be sufficient to ignore that difference and only break the build for the host triplet? It looks like the [rust-lang/cargo#9322](https://github.com/rust-lang/cargo/pull/9322) PR was merged June 1st, so I would guess it's in the nightly branch at least. So if you set `RUSTFLAGS` consistently and it's ignored everywhere except when `--target` matches the host (and maybe only nightly for now), it should still fail at least one check.

Ah, never mind. I just tried that against a local nightly toolchain and it doesn't work. Maybe it's not in nightly yet, or maybe I'm misunderstanding the fix in https://github.com/rust-lang/cargo/pull/9322.

**Comment by riverar** [comment]
@wravery In this case, we were working a bit too hard. We configured the default toolchain (i.e. x86 / x64) during CI but then also did a bit of extra work for cross-compilation (e.g. added targets via rustup, specified `--targets` during build) that wasn't needed and wasn't a noop as expected. (RUSTFLAGS is ignored!)

New PR #15 is failing expectedly now.

**Pull request closed without merging**
